theme: jekyll-theme-minimal
#theme: jekyll-theme-slate
title: Hlavi's homepage
exclude:
  - readme.md
  - .github/
header_pages:
  - index.html
author: Hlavi
github_username:  Hlavi71
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

